### ISSUE TITLE
Test Issues on AWS

### ISSUE THREAD

**Issue by pdeperio** [drinkingkazu/mlws-2019-04-srn#1]
Logged into Thomas' AWS instance (described [here](https://mlw.hyperk.ca/internal/computing-resources)) via:
```
ssh ec2-user@18.222.82.69
```
Checked out this repo to:
```
/data/mlws-2019-04-srn
```
and copied data from Cedar:```/scratch/prouse/ML_MC/numpy``` to ```/data/hkml_data``` (~1 GB so far).

Then tried running the example training command under the following 3 environments, resulting in various dependency errors:

1. **Kazu's Singularity Container** ([this one?](https://www.singularity-hub.org/containers/6596))
```
singularity exec --bind /data --nv ~/kazu_container/kazu_container.simg bash
export CUDA_VISIBLE_DEVICES=0
DATADIR=/data/hkml_data
COMMAND="/data/mlws-2019-04-srn/bin/spd.py train -ld log -wp /data/weights/snapshot -chks 100 -nc 2 -it 30000 -bs 32 -mbs 32 --gpus 0  -rs 1 -mn SimpleResNet10 -io spd_buffer -id ${DATADIR}/eminus,${DATADIR}/gamma/ -nr 10 -dd 3 -ss 128 -uf 16"
${COMMAND}

THCudaCheck FAIL file=torch/csrc/cuda/Module.cpp line=34 error=35 : CUDA driver version is insufficient for CUDA runtime version
```
My Singularity experience is nil, but I guess the version within the container needs to be updated to 10.0?

2. **Deep Learning AMI: PyTorch with Python3 (CUDA 10.0 and Intel MKL)** 
```
source activate pytorch_p36
python ${COMMAND}

ModuleNotFoundError: No module named 'dataloader'
```
Are you still using Python2? ;)

3. **Deep Learning AMI: PyTorch with Python2 (CUDA 10.0 and Intel MKL)** 
```
source activate pytorch_p27
python ${COMMAND}

ImportError: No module named sparseconvnet
```
This last attempt got the furthest, and actually spent some time training before the error. But it also showed ```GPUS = [0]``` in the initialization output, is this ok? (Edit: added ```--nv``` flag to singularity command above, as per @drinkingkazu's comment below.)

**Comment by thomaslindner** [comment]
The GPUS = [0] seems to be the result of something you set.  In your command I changed 
--gpus 0
to 
--gpus 1

But then I get a different error:

RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /opt/conda/conda-bld/pytorch_1544194558701/work/torch/csrc/cuda/Module.cpp:34

**Comment by drinkingkazu** [comment]
You must enable GPUs when you instantiate the container:
```
singularity exec --nv myimage bash
```
Do you still see an error with this?

**Comment by drinkingkazu** [comment]
Also, in case this can be useful... though you probably read more documentation by now...
https://github.com/DeepLearnPhysics/playground-singularity/wiki/2.-Getting-started

**Comment by thomaslindner** [comment]
Hmm, interesting.  Now I do 

singularity exec --nv ~/kazu_container/kazu_container.simg ${COMMAND}

and get

RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at torch/csrc/cuda/Module.cpp:34

So now the error is the same with singularity and with the "PyTorch with Python2" tools.

Kazu, as a reminder I posted information here

https://mlw.hyperk.ca/internal/computing-resources

that would allow you to logon to the instance yourself.

**Comment by drinkingkazu** [comment]
Hi there,

Thanks for the log in info! I tried and now it works.
The issue was that somehow `.bashrc` was set up, and when you do `singularity exec --nv myimg bash`, that runs this config script which overwrites which python to use. 
If you try `which python` you see it's using anaconda3 installation, which is not from container.
I looked at `.bashrc` and it's sourcing `.dlamirc`. 
I commented out that line and now the container works as expected.
Would you try and, if it works, close the ticket?

**Comment by drinkingkazu** [comment]
Sorry for clarity, .bashrc is expected to run because I suggested to execute `bash`. What I meant by not expecred is that it overwrote the software setup. I should have been clear on this instruction. I'm sorry...

**Comment by thomaslindner** [comment]
Hmm, well I agree that that seems to clear up which version of python we are running.  But it does not seem to fix the problem with CUDA not finding the GPU

[ec2-user@ip-172-31-16-180 ~]$ singularity exec --nv ~/kazu_container/kazu_container.simg bash
ec2-user@ip-172-31-16-180:~$ python --version
Python 2.7.12
ec2-user@ip-172-31-16-180:~$ export DATADIR=/home/ec2-user/hkml_data
ec2-user@ip-172-31-16-180:~$ /home/ec2-user/mlws-2019-04-srn/bin/spd.py train -ld log -wp weights/snapshot -chks 100 -nc 2 -it 30000 -bs 32 -mbs 32 --gpus 1  -rs 1 -mn SimpleResNet10 -io spd_buffer -id ${DATADIR}/eminus,${DATADIR}/gamma/ -nr 10 -dd 3 -ss 128 -uf 16
-- CONFIG --
LEARNING_RATE = 0.001
...
  File "/home/ec2-user/mlws-2019-04-srn/spd/main_funcs.py", line 47, in prepare
    torch.cuda.set_device(flags.GPUS[0])
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/__init__.py", line 264, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at torch/csrc/cuda/Module.cpp:34

**Comment by pdeperio** [comment]
After restarting the instance, and trying @thomaslindner's [last recipe](https://github.com/drinkingkazu/mlws-2019-04-srn/issues/1#issuecomment-473442359), I get an unknown error:
```
THCudaCheck FAIL file=torch/csrc/cuda/Module.cpp line=34 error=30 : unknown error
```

**Comment by drinkingkazu** [comment]
Confirmed. I remember seeing this error from testing the image on TitanRTX gpu w/ cuda10. Likely this is due to the fact that the driver (firmware) installed is later version that supports cuda10 but not 9. The image uses cuda9 right now. I’ll brew cuda10 image to see if that can mitigate the issue...

**Comment by pdeperio** [comment]
We seemed to have worked this out on [Slack](https://mlwatercherenkov.slack.com/archives/CH5AD8Z53/p1553111741048300). There were two issues:

- ```--gpu 1``` should be ```--gpu 0``` (this is an index, not a flag nor total number)
- ```export CUDA_VISIBLE_DEVICES=0``` is required (I guess to also force system to use 0'th GPU (recipe updated in original post above)

cuda9 and cuda10 mismatch doesn't seem to be an issue. (Edit: Wrong, see below.)

**Comment by pdeperio** [comment]
@drinkingkazu Actually, the previous success was fake, I couldn't reproduce anymore after rebooting/logging back in:

```
singularity exec --bind /data --nv ~/kazu_container/kazu_container.simg bash
export CUDA_VISIBLE_DEVICES=0
DATADIR=/data/hkml_data
COMMAND="/data/mlws-2019-04-srn/bin/spd.py train -ld log -wp /data/weights/snapshot -chks 100 -nc 2 -it 30000 -bs 32 -mbs 32 --gpus 0  -rs 1 -mn SimpleResNet10 -io spd_buffer -id ${DATADIR}/eminus,${DATADIR}/gamma/ -nr 10 -dd 3 -ss 128 -uf 16"
${COMMAND}

THCudaCheck FAIL file=torch/csrc/cuda/Module.cpp line=34 error=30 : unknown error
```

I guess I had an unclean environment from:
```
export PATH=$HOME/anaconda3/bin/:$PATH
source activate pytorch_p27
```
which propagated into the container somehow and made it work.

Now I switched the system default CUDA to version 10 using [the instructions](https://docs.aws.amazon.com/dlami/latest/devguide/tutorial-base.html) @thomaslindner found, and now it works for real I think.

--------------------
Test commands for future reference:
```
python -c "import torch;print torch.cuda.is_available()"
python -c "import torch;print torch.Tensor([0.0]).cuda()"
```

**Comment by thomaslindner** [comment]
I still find this problem to be occurring when I try running on a new instance (cloned from our current instance), but in an inconsistent way.  Initially I find that I am still getting the error about "line 34.. .unknown error".  But then I run a bunch of sets of commands in some sort of order and the error goes away... 

There is something unstable with our steps... not clear if I have permanently fixed the problem for the new instance or just temporarily.

**Comment by thomaslindner** [comment]
I looked at this problem more.  There is definitely something to do with the NVIDIA card or driver that is not initialized properly with the existing singularity instance.  

Symptoms:
1) If I reboot the instance, I find that I get the following when I start singularity container:
singularity exec --bind /data --nv  /home/ec2-user/kazu_container/kazu_container.simg bash
python -c "import torch;print torch.cuda.is_available()"
False

2) However, if I do this
export PATH=$HOME/anaconda3/bin/:$PATH
 source activate pytorch_p27
(pytorch_p27) [ec2-user@ip-172-31-19-226 ~]$ python -c "import torch;print torch.cuda.is_available()"
True

then it will also work when I start singularity container
singularity exec --bind /data --nv /home/ec2-user/kazu_container/kazu_container.simg bash
python -c "import torch;print torch.cuda.is_available()"
True

3) The problem is not related to the shell environment.  The 'fix' persists even after logging out and back in.

4) Starting the 'pytorch_p27' environment is not sufficient.  I need to actually run the command "python -c "import torch;print torch.cuda.is_available()"" within that environment.  Otherwise the fix is not applied.

**Comment by pdeperio** [comment]
FYI, when running [the MNIST Pytorch example](https://github.com/WatChMaL/ExampleNotebooks/blob/master/MNIST%20LeNet.ipynb), this error appears as:
```
"Cannot re-initialize CUDA in forked subprocess. "
RuntimeError: cuda runtime error (30) : unknown error at /pytorch/aten/src/THC/THCGeneral.cpp:51
```
